---
name: Release
on:
  # https://github.com/actions/runner/issues/1007
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Launch goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
